# Generated by Django 5.0.6 on 2024-08-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('classroom', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('semester', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
