# Generated by Django 5.0.6 on 2024-08-04 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('percentage_of_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submission_status', models.BooleanField(default=False)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('grade_received', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='website.record')),
            ],
        ),
    ]
